# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

environment:
  BASH_ENV: "~/.bashrc"

references:
  common_steps: &common_steps

    environment:
          BASH_ENV: "~/.bashrc"

    steps:
      - checkout
      - run : git config --global user.email "you@example.com" && git config --global user.name "yn"
      - run: npm install
      - run: npm run test-all && echo 1 > /tmp/test
      - store_artifacts:
          path: coverage
          destination: prefix
      - store_test_results:
          path: coverage/lcov-report/

      - run: node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info && echo 1 > /tmp/coverage


jobs:
  node11:
    docker:
      - image: node:11
    <<: [ *common_steps ]

workflows:
  version: 2
  build:
    # Evidently CircleCI can't cope with unique job
    # names unless workflows are used.
    jobs:
      - node11
