# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

environment:
  BASH_ENV: "~/.bashrc"

references:
  common_steps: &common_steps
    environment:
          BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      - run: apt-get update && apt-get -y install expect
      - run: expect -c "spawn ssh-add - <<< "${SSH_KEY}" expect -re \"Enter passphrase for (stdin):\"; send \"n\";"
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git config --global user.email "you@example.com" && git config --global user.name "yn"
      - run: ./bin/node-modules-cache-key.js > ./npm-hash
      - restore_cache:
          keys:
            - deps-{{ checksum "npm-hash" }}
      - run: npm install
      - run: ./bin/node-modules-cache-key.js > ./npm-hash
      - restore_cache:
          keys:
            - deps-{{ checksum "npm-hash" }}
      - run: npm run test-all && echo 1 > /tmp/test
      - save_cache:
          key: deps-{{ checksum "npm-hash" }}
          paths:
            #beginning package template
            - packages/cowlog/node_modules
            - packages/directory-fixture-provider/node_modules
            - packages/dsl-framework/node_modules
            - packages/dsl-framework/examples/auto-publish/parenting/node_modules
            - packages/generic-text-linker/node_modules
            - packages/refresh-me/node_modules
            - packages/require-a-lot/node_modules
            #end package template
      - store_artifacts:
          path: coverage
          destination: prefix
      - store_test_results:
          path: coverage/lcov-report/
      - run: node_modules/codeclimate-test-reporter/bin/codeclimate.js < ./coverage/lcov.info && echo 1 > /tmp/coverage


jobs:
  node11:
    docker:
      - image: node:11
    <<: [ *common_steps ]

workflows:
  version: 2
  build:
    # Evidently CircleCI can't cope with unique job
    # names unless workflows are used.
    jobs:
      - node11
